### ISSUE TITLE
Inferencing in Real time

### ISSUE THREAD

**Issue by jatinarora999** [shirley-wu/text_to_table#5]
Hi @shirley-wu, I am curious if there is a way to translate the text into a table in real time rather than reading the text from the test data file?

**Comment by shirley-wu** [comment]
Hi, thanks for your interests in our work! Do you mean you want to call the text-to-table model by code rather than by bash scripts? If so, yes you can do that.

Since our code is based on fairseq framework, you should use fairseq APIs to implement that. You can check the source code for `fairseq-interactive` script [here](https://github.com/facebookresearch/fairseq/blob/v0.10.2/fairseq_cli/interactive.py) and borrow their code. Basically you need to (1) setup the task, (2) load the model, (3) tokenize your input text and make it into a batch, and (4) call the model's generation function. You may also want to check their [documents](https://fairseq.readthedocs.io/en/v0.10.2/). 

Please let me know if this cannot resolve your question.
